#!/usr/bin/env bash
# Copyright (c) 2016-2019, w0rp <devw0rp@gmail.com> {{{
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.  2. Redistributions in binary
# form must reproduce the above copyright notice, this list of conditions and
# the following disclaimer in the documentation and/or other materials provided
# with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# }}}

# For more info about the 'set' command, see
# https://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin
set -e
set -u

docker_image=kkoomen/doge
current_docker_image_id=17b41b268a58

DOGE_DOCKER_IMAGE="$docker_image"
export DOGE_DOCKER_IMAGE

verbose_flag=''
verbose=0
run_vim_81_tests=1
run_linter=1

while [ $# -ne 0 ]; do
  case $1 in
  -v)
      verbose_flag='-v'
      verbose=1
      shift
  ;;
  --vim-81-only)
    run_linter=0
    shift
  ;;
  --linter-only)
    run_vim_81_tests=0
    shift
  ;;
  --)
      shift
      break
  ;;
  -?*)
      echo "Invalid argument: $1" 1>&2
      exit 1
  ;;
  *)
      break
  ;;
  esac
done

# Allow tests to be passed as arguments.
if [ $# -ne 0 ]; then
  tests="$*"

  # Do not run any other tools when targeting specific tests.
  run_linter=0
else
  tests='test/*.vader test/*/*.vader test/*/*/*.vader'
fi

# Delete .swp files in the test directory, which cause Vim 8 to hang.
find test -name '*.swp' -delete

docker images -q $DOGE_DOCKER_IMAGE | grep "^$current_docker_image_id" > /dev/null \
  || docker pull "$docker_image"

output_dir=$(mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir')

trap '{ rm -rf "$output_dir"; }' EXIT

# Used for killing tests when you kill the script.
cancel_tests() {
  set +e

  if [ -n "$pid_list" ]; then
    for pid in $pid_list; do
      kill "$pid"
      wait "$pid"
    done
  fi

  docker kill $(docker ps -a -q --filter ancestor="$docker_image" --format='{{.ID}}') &> /dev/null

  if [ -d "$output_dir" ]; then
    rm -rf "$output_dir"
  fi

  echo
  exit 1
}

trap cancel_tests INT TERM

file_number=0
pid_list=''
for vim in $(docker run --rm "$DOGE_DOCKER_IMAGE" ls /vim-build/bin | grep '^vim'); do
  if ( [[ $vim =~ ^vim-v8.1 ]] && ((run_vim_81_tests)) ); then
      echo "Starting Vim: $vim..."
      file_number=$((file_number+1))
      scripts/run-vader-tests $verbose_flag "$vim" "$tests" > "$output_dir/$file_number" 2>&1 &
      pid_list="$pid_list $!"
  fi
done

if ((run_linter)); then
    echo "Starting Vint..."
    file_number=$((file_number+1))
    scripts/run-vint > "$output_dir/$file_number" 2>&1 &
    pid_list="$pid_list $!"
fi

echo

failed=0
index=0

for pid in $pid_list; do
  this_failed=0
  index=$((index+1))

  if ! wait "$pid"; then
    failed=1
    this_failed=1
  fi

  if ( [[ -f "$output_dir/$index" ]] && ((this_failed)) ) || ((verbose)); then
    cat "$output_dir/$index"
  fi
done

if ((failed)); then
  echo 'Something went wrong!'
else
  echo 'All tests passed!'
fi

exit $failed
